### ISSUE TITLE
tracing_smoke_test fails on "thor" test machine

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1021]
For about a month we had the nightly tests failing on "tracing_smoke_test". It failed just when running on the "thor" test machines, and succeeds when I moved it to a different one. It also succeeds on my own build machines.
To run just this specific test, run:
```
scripts/test.py --name tracing_smoke_test
```
The test fails because scripts/trace.py runs gdb, as:
```
gdb build/release/loader.elf -batch -iex "set auto-load safe-path ." -ex conn -ex "osv trace save tracefile"
```
And that fails with the following message:
```
gdb build/release/loader.elf -batch -iex "set auto-load safe-path ." -ex conn -ex "osv trace save tracefile"
Traceback (most recent call last):
  File "/home/nyh/osv/scripts/loader.py", line 1585, in <module>
    setup_libstdcxx()
  File "/home/nyh/osv/scripts/loader.py", line 1109, in setup_libstdcxx
    exec(compile(open(script).read(), script, 'exec'))
  File "/usr/share/gdb/python/../auto-load/usr/lib64/libstdc++.so.6.0.24-gdb.py", line 60, in <module>
    from libstdcxx.v6 import register_libstdcxx_printers
ImportError: cannot import name 'register_libstdcxx_printers'
```

**Comment by wkozaczuk** [comment]
Is this a duplicate of #988?

**Comment by nyh** [comment]
No, I think it's completely different... Issue #988 had a problem with the actual traces received by the test, and in this test, we couldn't even run gdb - and probably had something to do with the setup on that specific machine that I was never able to reproduce on any other machine.
