### ISSUE TITLE
scripts/build check tracing_smoke_test fails on fresh Docker image

### ISSUE THREAD

**Issue by Mason-D** [cloudius-systems/osv#1063]
Hello, 

I am running a fresh build of the Docker image at `docker/Dockerfile`, but `tracing_smoke_test` still fails.

My steps:
* `docker build -t osv/builder .` (I've also tried with  _--no-cache_ to ensure my image is fresh)
* `docker run -it --privileged osv/builder`
* `./scripts/build check`

The check fails on `tracing_smoke_test` with the following:
```TEST tracing_smoke_test                 Test tracing_smoke_test FAILED
Traceback (most recent call last):
  File "/git-repos/osv/scripts/test.py", line 204, in <module>
    main()
  File "/git-repos/osv/scripts/test.py", line 183, in main
    run_tests()
  File "/git-repos/osv/scripts/test.py", line 174, in run_tests
    run(tests_to_run)
  File "/git-repos/osv/scripts/test.py", line 94, in run
    run_test(test)
  File "/git-repos/osv/scripts/test.py", line 69, in run_test
    test.run()
  File "/git-repos/osv/scripts/tests/testing.py", line 52, in run
    self.f()
  File "/git-repos/osv/scripts/tests/test_tracing.py", line 52, in tracing_smoke_test
    assert('0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from' in tcpdump)
AssertionError```

**Comment by wkozaczuk** [comment]
I have just tried to run all unit tests including this one in one of my containers (I think it is Ubuntu 19.04 based) and they all pass including the `tracing_smoke_test`. This looks like a setup issue. Which docker file are you using - Ubuntu or Fedora? Have you modified it to use a different base?

Have you tried to run the individual test with verbose like this?
```
./scripts/test.py -v --name tracing_smoke_test
```
Based on the error it seems to be networking related. Do you have KVM enabled? On Ubuntu you can run `kvm-ok`, on Fedora check if you have access to `/dev/kvm`.

**Comment by Mason-D** [comment]
The test is failing on the Fedora image. KVM is enabled and accessible. The image is fresh and unmodified, so just using the  setup and configuration the base image. The test fails when running the entire test-suite (`./scripts/build check`) AND when running the test isolated, as you suggested.

Alternatively, when running `./scripts/check` on the Ubuntu image, I do not see this issue. It seems like this is isolated to the Fedora image.

**Comment by wkozaczuk** [comment]
Which version of Fedora?

**Comment by Mason-D** [comment]
From `docker/Dockerfile.Fedora`:
```
#FROM fedora:27 #On Jenkins build machine
FROM fedora:29
```

It's using **Fedora 29**, but the comment suggesting Fedora27 intrigued me. When changing the image to use Fedora27, the test passes.

**Comment by wkozaczuk** [comment]
I just tried it with Fedora 29 in a container and I cannot reproduce it.

Can you make this change the test to print the trace output:
```
diff --git a/scripts/tests/test_tracing.py b/scripts/tests/test_tracing.py
index 3a9fca70..da8ef8d6 100644
--- a/scripts/tests/test_tracing.py
+++ b/scripts/tests/test_tracing.py
@@ -49,6 +49,7 @@ def tracing_smoke_test():
         assert('192.168.122.1.67 > 255.255.255.255.68: BOOTP/DHCP, Reply' in tcpdump)
 
         tcpdump = subprocess.check_output([trace_script, 'list', '--tcpdump']).decode()
+        print(tcpdump)
         assert('0.0.0.0.68 > 255.255.255.255.67: BOOTP/DHCP, Request from' in tcpdump)
         assert('192.168.122.1.67 > 255.255.255.255.68: BOOTP/DHCP, Reply' in tcpdump)
     finally:
```

Most likely yours will not have that expected string. Here is my output - https://gist.github.com/wkozaczuk/0a0e2fc9207d93f9f2dcaeb0d490290b

**Comment by wkozaczuk** [comment]
I think I may have inadvertently re-created the same issue. It turns out the `scripts/trace.py` called by `test_tracing.py` execs `tcpdump` that may be misbehaving in docker container.

These lines are key from the printout I captured:
```
0xffff800001d81040 >init            0         0.166967307 net_packet_out       dropped privs to tcpdump
0xffff800001d81040 >init            0         0.166973723 sched_wait           
0xffff800001d9b040 virtio-net-rx    0         0.167085032 sched_wait_ret       
0xffff800001d9b040 virtio-net-rx    0         0.167087138 net_packet_in        dropped privs to tcpdump
0xffff800001d9b040 virtio-net-rx    0         0.167089912 net_packet_in        dropped privs to tcpdump
0xffff800001d9b040 virtio-net-rx    0         0.167093236 sched_wait           
0xffff800002639040 dhcp             0         0.167093524 sched_wait_ret       
0xffff800002639040 dhcp             0         0.167102509 net_packet_out       dropped privs to tcpdump
0xffff800002639040 dhcp             0         0.167107558 sched_wait           
0xffff800001d9b040 virtio-net-rx    0         0.167145030 sched_wait_ret       
0xffff800001d9b040 virtio-net-rx    0         0.167145476 net_packet_in        dropped privs to tcpdump
0xffff800001d9b040 virtio-net-rx    0         0.167145886 net_packet_in        dropped privs to tcpdump
0xffff800001d9b040 virtio-net-rx    0         0.167146656 sched_wait           
0xffff800002639040 dhcp             0         0.167146932 sched_wait_ret       
0xffff800002639040 dhcp             0         0.167152446 vfs_ioctl            1 0x5401
0xffff800002639040 dhcp             0         0.167152895 vfs_ioctl_ret        
0xffff800002639040 dhcp             0         0.167153228 vfs_pwritev          1 0xffff80000293b9a0 0x2 0x-1
0xffff800002639040 dhcp             0         0.167728358 vfs_pwritev_ret      0x15
0xffff800002639040 dhcp             0         0.167742416 net_packet_out       dropped privs to tcpdump
0xffff800002639040 dhcp             0         0.167766830 net_packet_in        dropped privs to tcpdump
0xffff800001aa4040 netisr           0         0.167770007 sched_wait_ret       
0xffff800001aa4040 netisr           0         0.167770720 net_packet_handling  dropped privs to tcpdump
```

When I execute tcpdump in the same container like the script I see this:
```
tcpdump
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
````

when I execute with same options as the `scripts/trace.py` I do not see these warnings:
```
tcpdump -nn -t -r -
```

All in all, I am not sure what exactly is wrong.

**Comment by Mason-D** [comment]
Okay, did some digging and discovered some interesting things. 

By default, tcpdump drops privilege when running as root, generally to the tcpdump user. This is happening on both Fedora27 and Fedora29. BUT, these two versions of Fedora use different versions of tcpdump, 4.9.1 and 4.9.3 respectively. By downgrading tcpdump versions, I discovered that the line `dropped privs to <user>`, where user is tcpdump by default, was added in tcpdump 4.9.3. 

For reasons I am still unsure, this extra print breaks the test. I haven't gone to deep into understanding all the python running here, but maybe you can provide some insight as to why the extra line print breaks the test? If I downgrade tcpdump to 4.9.2, the test passes on Fedora29.
