### ISSUE TITLE
Cannot run YCSB with Redis on OSV

### ISSUE THREAD

**Issue by EEngblo** [cloudius-systems/osv#1074]
Hello, I'm trying to run YCSB with Redis on OSV yet it fails immediately after connection. I can use `redis-cli` and some commands to manipulate Redis, and `redis-benchmark` as well. However, it fails every time when I try to run YCSB workloads which successfully works with Redis that runs on the bare metal Linux.

I tried both bridged network and port forwarding with the vanilla code of OSV, but neither works. The command on Linux to run YCSB is:
```shell
$ ./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=127.0.0.1" -p "redis.port=7777" > outputLoad.txt

Loading workload...
Starting test.
2020-02-26 17:41:11:825 0 sec: 0 operations; est completion in 0 second
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:151)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.zadd(Jedis.java:1385)
	at site.ycsb.db.RedisClient.insert(RedisClient.java:141)
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
	at site.ycsb.ClientThread.run(ClientThread.java:135)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196)
```

And the OSV side is:
```shell
sudo ./scripts/run.py -V -m 8192 -e "./redis-server --protected-mode no --loglevel verbose" --forward tcp::7777-:6379
virtio_uverbs_pci_class_init
virtio_uverbs_pci_class_init done
OSv v0.54.0-121-gd36bbe23
4 CPUs detected
Firmware vendor: SeaBIOS
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=268435456
random: virtio-rng registered as a source.
random: intel drng, rdrand registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting rofs at /rofs
failed to mount /rofs, error = No error information
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
VFS: mounting sysfs at /sys
BSD shrinker: event handler list found: 0xffffa00100700f80
	BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/43 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1082689702]
[I/43 dhcp]: Waiting for IP...
[I/221 dhcp]: Received DHCPOFFER message from DHCP server: 192.168.122.1 regarding offerred IP address: 192.168.122.15
[I/221 dhcp]: Broadcasting DHCPREQUEST message with xid: [1082689702] to SELECT offered IP: 192.168.122.15
[I/221 dhcp]: Received DHCPACK message from DHCP server: 192.168.122.1 regarding offerred IP address: 192.168.122.15
[I/221 dhcp]: Server acknowledged IP 192.168.122.15 for interface eth0 with time to lease in seconds: 86400
eth0: 192.168.122.15
[I/221 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Booted up in 311.26 ms
Cmdline: ./redis-server --protected-mode no --loglevel verbose
random: blocking on read.
random: device unblocked.
0:M 26 Feb 08:41:01.929 # Not listening to IPv6: unsupproted
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.8 (24577fb0/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 0
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

0:M 26 Feb 08:41:01.958 # Server started, Redis version 3.2.8
0:M 26 Feb 08:41:01.959 * The server is now ready to accept connections on port 6379
0:M 26 Feb 08:41:01.961 - 0 clients connected (0 slaves), 830416 bytes in use
0:M 26 Feb 08:41:06.969 - 0 clients connected (0 slaves), 830416 bytes in use
0:M 26 Feb 08:41:11.828 - Accepted 192.168.122.1:58732


=== REDIS BUG REPORT START: Cut & paste starting from here ===
0:M 26 Feb 08:41:11.858 # === ASSERTION FAILED OBJECT CONTEXT ===
0:M 26 Feb 08:41:11.859 # Object type: 0
0:M 26 Feb 08:41:11.860 # Object encoding: 8
0:M 26 Feb 08:41:11.861 # Object refcount: 2
0:M 26 Feb 08:41:11.862 # Object raw string len: 23
0:M 26 Feb 08:41:11.863 # Object raw string content: "user7109110581138159243"
0:M 26 Feb 08:41:11.865 # === ASSERTION FAILED ===
0:M 26 Feb 08:41:11.866 # ==> t_zset.c:921 'sptr != NULL' is not true
0:M 26 Feb 08:41:11.867 # (forcing SIGSEGV to print the bug report.)
0:M 26 Feb 08:41:11.869 # Redis 3.2.8 crashed by signal: 11
0:M 26 Feb 08:41:11.870 # Crashed running the instuction at: 0x10000046f10d
0:M 26 Feb 08:41:11.871 # Accessing address: 0xfffffffffffff000
0:M 26 Feb 08:41:11.873 # Failed assertion: sptr != NULL (t_zset.c:921)

------ STACK TRACE ------
EIP:
_serverAssert+109 [0x10000046f10d]

Backtrace:
logStackTrace+107 [0x100000470c8b]
sigsegvHandler+177 [0x1000004713b1]
call_signal_handler+305 [0x4037d3d1]
???+1077476027 [0x4038fabb]
_serverAssert+109 [0x10000046f10d]
zzlFind+310 [0x10000045c546]
zaddGenericCommand+1196 [0x10000045d3dc]
call+113 [0x100000435c91]
processCommand+1119 [0x100000438f9f]
processInputBuffer+277 [0x1000004460d5]
???+4389668 [0x10000042fb24]
aeMain+43 [0x10000042fe9b]
main+506 [0x10000042cc2a]
osv::application::run_main()+61 [0x404227ad]
osv::application::main()+162 [0x4020dac2]
???+1078077817 [0x40422979]
???+1078322374 [0x4045e4c6]
thread_main_c+39 [0x403efe47]
call_signal_handler_thunk+0 [0x4038fab3]

------ INFO OUTPUT ------
# Server
redis_version:3.2.8
redis_git_sha1:24577fb0
redis_git_dirty:0
redis_build_id:d6ea15c234b9fa00
redis_mode:standalone
os:Linux 3.7.0 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:7.4.0
process_id:0
run_id:12dafd3da5672ca1692ce2119816758fcf362fdf
tcp_port:6379
uptime_in_seconds:10
uptime_in_days:0
hz:10
lru_clock:5648167
executable:/./redis-server
config_file:

# Clients
connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

# Memory
used_memory:918448
used_memory_human:896.92K
used_memory_rss:222398775296
used_memory_rss_human:207.12G
used_memory_peak:918448
used_memory_peak_human:896.92K
total_system_memory:8589398016
total_system_memory_human:8.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:242146.30
mem_allocator:libc

# Persistence
loading:0
rdb_changes_since_last_save:29
rdb_bgsave_in_progress:0
rdb_last_save_time:1582706461
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok

# Stats
total_connections_received:1
total_commands_processed:29
instantaneous_ops_per_sec:0
total_net_input_bytes:19858
total_net_output_bytes:131
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0

# Replication
role:master
connected_slaves:0
master_repl_offset:0
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.00
used_cpu_user:0.36
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Commandstats
cmdstat_zadd:calls=14,usec=154,usec_per_call=11.00
cmdstat_hmset:calls=15,usec=169,usec_per_call=11.27

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=16,expires=0,avg_ttl=0
hash_init_value: 1583078318

------ CLIENT LIST OUTPUT ------
id=2 addr=192.168.122.1:58732 fd=5 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=zadd

------ CURRENT CLIENT INFO ------
id=2 addr=192.168.122.1:58732 fd=5 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=zadd
argv[0]: 'ZADD'
argv[1]: '_indices'
argv[2]: '-1.395012922E9'
argv[3]: 'user7109110581138159243'
0:M 26 Feb 08:41:11.946 # key '_indices' found in DB containing the following object:
0:M 26 Feb 08:41:11.948 # Object type: 3
0:M 26 Feb 08:41:11.949 # Object encoding: 5
0:M 26 Feb 08:41:11.950 # Object refcount: 1
0:M 26 Feb 08:41:11.951 # Sorted set size: 14

------ REGISTERS ------
0:M 26 Feb 08:41:11.953 #
RAX:0000000000000000 RBX:0000000000000399
RCX:0000200000200780 RDX:00000000408958b8
RDI:00000000408958b8 RSI:fffffffffffff958
RBP:00001000004c1fdc RSP:0000200000200c60
R8 :00000000409245d8 R9 :00000000409245d8
R10:0000000000000000 R11:0000000000000000
R12:00001000004c20fd R13:ffffa001005aa888
R14:0000200000200d20 R15:0000000000000000
RIP:000010000046f10d EFL:0000000000000000
CSGSFS:0000000000000000
0:M 26 Feb 08:41:11.962 # (0000200000200c6f) -> 000000004036e2e6
0:M 26 Feb 08:41:11.963 # (0000200000200c6e) -> c1d4c98d4e800000
0:M 26 Feb 08:41:11.965 # (0000200000200c6d) -> ffff800102ad3048
0:M 26 Feb 08:41:11.967 # (0000200000200c6c) -> 0000000000000010
0:M 26 Feb 08:41:11.968 # (0000200000200c6b) -> 000010000045d3dc
0:M 26 Feb 08:41:11.969 # (0000200000200c6a) -> 0000000000000000
0:M 26 Feb 08:41:11.971 # (0000200000200c69) -> ffffa00101dc4508
0:M 26 Feb 08:41:11.973 # (0000200000200c68) -> 0000000000000003
0:M 26 Feb 08:41:11.974 # (0000200000200c67) -> ffffa001005aa888
0:M 26 Feb 08:41:11.976 # (0000200000200c66) -> ffffa001005a3038
0:M 26 Feb 08:41:11.977 # (0000200000200c65) -> ffff800102ad3048
0:M 26 Feb 08:41:11.979 # (0000200000200c64) -> ffffa001005a3040
0:M 26 Feb 08:41:11.980 # (0000200000200c63) -> 000010000045c546
0:M 26 Feb 08:41:11.982 # (0000200000200c62) -> 00001000004c2460
0:M 26 Feb 08:41:11.983 # (0000200000200c61) -> ffffa00100572408
0:M 26 Feb 08:41:11.985 # (0000200000200c60) -> ffffa0010057b595

------ FAST MEMORY TEST ------
pthread_cancel() stubbed
*** Preparing to test memory region 1000006f8000 (86016 bytes)
*** Preparing to test memory region 200000002000 (1044480 bytes)
*** Preparing to test memory region 200000102000 (1044480 bytes)
*** Preparing to test memory region 200000401000 (4190208 bytes)
*** Preparing to test memory region 200000801000 (4190208 bytes)
.page fault outside application, addr: 0x0000200000101000
[registers]
RIP: 0x000000004037d602 <memcpy_repmov_ssse3+66>
RFL: 0x0000000000010212  CS:  0x0000000000000008  SS:  0x0000000000000010
RAX: 0x0000000000014000  RBX: 0x00001000006f8000  RCX: 0x0000000000012110  RDX: 0x0000000000014000
RSI: 0x00001000006f9ef0  RDI: 0x0000200000101000  RBP: 0x00002000002001b0  R8:  0x00000000409245c0
R9:  0x00000000409245c0  R10: 0x0000000000000000  R11: 0xffffa001006fab00  R12: 0x00002000000ff110
R13: 0x00000000409245c0  R14: 0x0000000000000000  R15: 0xffffa001006fab00  RSP: 0x00002000000ff0c0
Aborted

[backtrace]
0x000000004032cc55 <???+1077070933>
0x000000004032f4ba <mmu::vm_fault(unsigned long, exception_frame*)+234>
0x000000004038fcf6 <page_fault+166>
0x000000004038eb36 <???+1077472054>
0x0000100000471456 <sigsegvHandler+342>
```

I wonder whether the problem happens on only my machine or there is a problem in OSV. Could you like to check whether you can run YCSB or not, please?

Thanks in advance!

**Comment by wkozaczuk** [comment]
Thanks for reporting this issue. After some digging it looks, we have a bug in `memmove()` implementation. I think we should have a fix pretty soon,
