### ISSUE TITLE
Grep perl extension causes building failure

### ISSUE THREAD

**Issue by milisarge** [cloudius-systems/osv#1081]
Building into build/release.x64
  GEN gen/include/osv/version.h
grep: support for the -P option is not compiled into this --disable-perl-regexp binary
grep: support for the -P option is not compiled into this --disable-perl-regexp binary
mkdir -p install/lua_modules
/opt/osv/scripts/manifest_from_host.sh -l  > usr.manifest
make: *** [Makefile:17: module] Error 1
Using image config: /opt/osv/images/default.py
Importing /opt/osv/modules/cli/module.py
Importing /opt/osv/modules/lua/module.py
Importing /opt/osv/modules/terminfo/module.py
Importing /opt/osv/modules/httpserver/module.py
Importing /opt/osv/modules/httpserver-html5-gui/module.py
Importing /opt/osv/modules/httpserver-api/module.py
Importing /opt/osv/modules/openssl/module.py
No module.py in /opt/osv/modules/libz
No module.py in /opt/osv/modules/libtools
Modules:
  lua
  terminfo
  libz
  openssl
  libtools
  httpserver-api
  httpserver-html5-gui
  httpserver.*
  cli
Traceback (most recent call last):
  File "scripts/module.py", line 280, in <module>
    args.func(args)
  File "scripts/module.py", line 233, in build
    make_modules(modules, args)
  File "scripts/module.py", line 124, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for lua
./scripts/build failed: ( for i in "${args[@]}";
do
    case $i in 
        *=*)
            export "$i"
        ;;
    esac;
done; export fs_type mode OSV_BUILD_PATH; export ARCH=$arch OSV_BASE=$SRC; scripts/module.py $j_arg build -c "$modules" $usrskel_arg $no_required_arg )

**Comment by wkozaczuk** [comment]
Can you give us more details which Linux distribution, version number you are getting this failure on? It looks like we might need to have `./scripts/setup.py` use `pcregrep` in some cases instead of grep. Or see if we can somehow remove the dependency on `-P` option.

**Comment by milisarge** [comment]
i am using scratch Linux distro, i thnk grep has not perl-regexp support.

**Comment by wkozaczuk** [comment]
Is it this one - http://www.linuxfromscratch.org/index.html? I do not think the `setup.py` supports it. Regardless, I think that `scripts/manifest_from_host.sh` relies on on perl support in grep (which is part of gnu grep like on Ubuntu and Fedora). I wonder what is the best course of action here, @nyh ?

**Comment by milisarge** [comment]
yes based on LFS but mostly distros without perl-regex, i tried to hack with pcregrep but it has too much usage. i thnk more painless solution needs.

**Comment by nyh** [comment]
@wkozaczuk is it hard to fix it to use "grep -e" (egrep) or python (which anyway we need for other stuff) or sed or a combination of greps instead of "grep -P"?
You can see in apps/*/{GET,Makefile} a lot of examples not using grep -P, for example:
```
ldd $BIN | grep lib$1.so | sed 's/ *[^ ] *\(.*\) => \(.*\) .*/\/\1: \2/'
find sample_codes/twitter -name '*.so' -exec ldd {} \;|awk '{print $$1,":",$$3}
```
and a lot of other bizarre pieces of code.

If you give me an example of a "grep -P" invocation which is hard to do without it, I will try to help you to convert to something which doesn't use "grep -P".
