### ISSUE TITLE
Clean fails

### ISSUE THREAD

**Issue by alexandermerritt** [cloudius-systems/osv#1097]
On a fresh clone to master and a submodule update, the following sequence of operations happens:

```bash
$ scripts/build -j10 mode=debug
# ... output snipped ...
# build is successful

$ scripts/build -j10 clean mode=debug
rm -rf build/debug.x64
rm -f build/debug build/last
++ pwd
+ OSV_BASE=/tmp/osv
+ ./scripts/module.py clean -q
rm -rf build/debug.x64
rm -f build/debug build/last
++ pwd
+ OSV_BASE=/tmp/osv
+ ./scripts/module.py clean -q
error: failed to parse manifest at `/tmp/osv/apps/rust-pie-httpserver/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
error: failed to parse manifest at `/tmp/osv/apps/rust-pie-example/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
make: [Makefile:9: clean] Error 101 (ignored)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

# I press control+c here.
^CTraceback (most recent call last):
  File "./scripts/module.py", line 280, in <module>
    args.func(args)
  File "./scripts/module.py", line 251, in clean
    shell=True, cwd=local_path, **extra_args):
  File "/usr/lib/python3.7/subprocess.py", line 341, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by nyh** [comment]
I have get a different error:
```
$ scripts/build clean
rm -rf build/release.x64
rm -f build/release build/last
++ pwd
+ OSV_BASE=/home/nyh/osv.tmp2/osv
+ ./scripts/module.py clean -q
rm: cannot remove 'usr.manifest': No such file or directory
make: *** [Makefile:20: clean] Error 1
Traceback (most recent call last):
  File "./scripts/module.py", line 280, in <module>
    args.func(args)
  File "./scripts/module.py", line 252, in clean
    raise Exception('\'make clean\' failed in ' + local_path)
Exception: 'make clean' failed in /home/nyh/osv.tmp2/osv/apps/Xapps
++ echo 'scripts/build failed: OSV_BASE=`pwd` ./scripts/module.py clean -q'
scripts/build failed: OSV_BASE=`pwd` ./scripts/module.py clean -q
++ exit 0
```
Both problems should be fixed...

**Comment by wkozaczuk** [comment]
@nyh I think the problem you reported was fixed with this commit https://github.com/cloudius-systems/osv-apps/commit/c68bbb737ebbe3fb5ef039383a30d83aa4cf7cf1 from May 12, 2020. Based on the date, it looks like you must have had a stale version of OSv.

**Comment by wkozaczuk** [comment]
Fixed by https://github.com/cloudius-systems/osv-apps/commit/184beda56c0bc01f8991ca2abcabacc6181ff57c
