### ISSUE TITLE
aarch64: some unit tests occasionally hang when running on QEMU in emulated mode (TCG)

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1127]
When running the unit tests using `scripts/test.py` sometimes one of the tests (it varies which one) enabled for AArch64 hangs. After connecting with gdb, I typically see this backtrace:
```
sched::cpu::do_idle (this=this@entry=0xffff8000407fe040) at core/sched.cc:454
454	        handle_incoming_wakeups();
(gdb) bt
#0  sched::cpu::do_idle (this=this@entry=0xffff8000407fe040) at core/sched.cc:454
#1  0x00000000402e5578 in sched::cpu::idle (this=0xffff8000407fe040) at core/sched.cc:472
#2  0x00000000402e55a0 in operator() (__closure=<optimized out>, __closure=<optimized out>) at core/sched.cc:165
#3  std::__invoke_impl<void, sched::cpu::init_idle_thread()::<lambda()>&> (__f=...) at build/downloaded_packages/aarch64/gcc/install/usr/include/c++/10/bits/invoke.h:60
#4  std::__invoke_r<void, sched::cpu::init_idle_thread()::<lambda()>&> (__fn=...) at build/downloaded_packages/aarch64/gcc/install/usr/include/c++/10/bits/invoke.h:153
#5  std::_Function_handler<void(), sched::cpu::init_idle_thread()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at build/downloaded_packages/aarch64/gcc/install/usr/include/c++/10/bits/std_function.h:291
#6  0x00000000402e5cb4 in sched::thread::main (this=0xffffa000408eea48) at core/sched.cc:1267
#7  sched::thread_main_c (t=0xffffa000408eea48) at arch/aarch64/arch-switch.hh:161
#8  0x00000000402c04e0 in reschedule_from_interrupt () at arch/aarch64/sched.S:50
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) disas
Dump of assembler code for function _ZN5sched3cpu7do_idleEv:
...
   0x00000000402e54f0 <+128>:	isb
   0x00000000402e54f4 <+132>:	wfi
=> 0x00000000402e54f8 <+136>:	mov	x0, x20
   0x00000000402e54fc <+140>:	bl	0x402e5294 <_ZN5sched3cpu23handle_incoming_wakeupsEv>
   0x00000000402e5500 <+144>:	ldr	x0, [x20, #4184]
   0x00000000402e5504 <+148>:	cbz	x0, 0x402e548c <_ZN5sched3cpu7do_idleEv+28>
...
```

Please note that the `wfi` instruction indicates that the idle thread is waiting for the next interrupt (from clock event?).

Dumping and examining all threads does not seem to indicate any deadlock and some of them have non-expired timers like so:
```
(gdb) osv info threads --timers
   1 (0xffffa000407f7798) reclaimer       cpu0 waiting    vruntime  9.53196e-23          126960 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
   2 (0xffffa00040836c18) page-access-sca cpu0 waiting    vruntime  6.68945e-20        13360064 pagecache::access_scanner::run() at core/pagecache.cc:695
    timers: 0.659470712
   3 (0xffffa00040837e00) page_pool_l2    cpu0 waiting    vruntime  1.61912e-21         1775984 memory::page_pool::l2::fill_thread() at core/mempool.cc:1437
   4 (0xffffa000408608d8) itimer-real     cpu? unstarted  vruntime            0               0 sched::thread_main_c(sched::thread*) at arch/aarch64/processor.hh:27
   5 (0xffffa00040861790) itimer-virt     cpu? unstarted  vruntime            0               0 sched::thread_main_c(sched::thread*) at arch/aarch64/processor.hh:27
   6 (0xffffa000408a3a60) balancer0       cpu0 waiting    vruntime  2.92361e-21         2971360 ?? at arch/aarch64/sched.S:50
    timers: 0.759490256
   7 (0xffffa000408a4878) rcu0            cpu0 waiting    vruntime  1.86865e-22          250768 osv::rcu::cpu_quiescent_state_thread::do_work() at core/rcu.cc:178
   8 (0xffffa000408b6858) page_pool_l1_0  cpu0 waiting    vruntime   1.3664e-21         1527776 memory::page_pool::l1::fill_thread() at core/mempool.cc:1349
   9 (0xffffa000408ca878) percpu0         cpu0 waiting    vruntime  5.20219e-23           69744 workman::call_of_duty() at core/percpu-worker.cc:92
  10 (0xffffa000408ee018) async_worker0   cpu0 waiting    vruntime    5.904e-23           79136 async::async_worker::run() at core/async.cc:158
  11 (0xffffa000408eea48) idle0           cpu0 running    vruntime          inf       488731088 std::_Function_handler<void(), sched::cpu::init_idle_thread()::<lambda()> >::_M_invoke(const std::_Any_data &) at build/downloaded_packages/aarch64/gcc/install/usr/include/c++/10/bits/std_function.h:291
  12 (0xffffa0004094e200) >init           cpu0 waiting    vruntime  5.81611e-23           66512 std::_Function_handler<void(), sched::thread::reaper::reaper()::<lambda()> >::_M_invoke(const std::_Any_data &) at build/downloaded_packages/aarch64/gcc/install/usr/include/c++/10/bits/std_function.h:291
  13 (0xffffa0004094e400) thread taskq    cpu0 waiting    vruntime  2.66132e-22          335856 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  14 (0xffffa0004094e600) callout         cpu0 waiting    vruntime  3.69129e-21         1470000 _callout_thread() at bsd/porting/callout.cc:138
    timers: 0.683496720
  15 (0xffffa0004094e800) system_taskq_0  cpu0 waiting    vruntime  3.46511e-23           34784 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  16 (0xffffa0004094ea00) system_taskq_1  cpu0 waiting    vruntime   2.2489e-23           19056 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  17 (0xffffa0004094ec00) system_taskq_2  cpu0 waiting    vruntime  1.21234e-23            5648 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  18 (0xffffa0004094ee00) system_taskq_3  cpu0 waiting    vruntime  1.21751e-23            5728 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  19 (0xffffa0004093f200) system_taskq_4  cpu0 waiting    vruntime  1.16839e-23            5072 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  20 (0xffffa0004093f400) system_taskq_5  cpu0 waiting    vruntime  6.95736e-23           79776 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  21 (0xffffa0004093f600) system_taskq_6  cpu0 waiting    vruntime  1.43981e-23            8560 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  22 (0xffffa0004093f800) system_taskq_7  cpu0 waiting    vruntime  1.21104e-23            5632 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  23 (0xffffa00040956400) solthread-0x401 cpu0 waiting    vruntime  4.44623e-22          542368 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
    timers: 1.074166688
  24 (0xffffa00040956600) solthread-0x401 cpu0 waiting    vruntime  1.81114e-22          212880 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
    timers: 1.075904032
  25 (0xffffa00040956800) netisr          cpu0 waiting    vruntime  7.46298e-22          696272 netisr_osv_thread_wrapper(void (*)(void*), void*) at bsd/sys/net/netisr1.cc:26
  26 (0xffffa000409b0400) >init           cpu0 waiting    vruntime  4.72807e-20        46337584 sched::thread::join() at core/sched.cc:1370
	joining on <optimized out>
  27 (0xffffa000409b0800) virtio-net-rx   cpu0 waiting    vruntime  1.41185e-26         1377632 virtio::virtio_driver::wait_for_queue(virtio::vring*, bool (virtio::vring::*)() const) at drivers/virtio.cc:158
  28 (0xffffa000409b0a00) virtio-tx-0     cpu0 waiting    vruntime  2.54797e-27          266368 osv::xmitter<virtio::net::txq, 4096u, std::function<bool ()>, boost::iterators::function_output_iterator<osv::xmitter_functor<virtio::net::txq> > >::poll_until() at include/osv/percpu_xmit.hh:395
  29 (0xffffa000409b0e00) virtio-blk      cpu0 waiting    vruntime  6.36696e-22          639504 virtio::virtio_driver::wait_for_queue(virtio::vring*, bool (virtio::vring::*)() const) at drivers/virtio.cc:158
  30 (0xffffa00040dd6200) virtio-rng      cpu0 waiting    vruntime   1.5722e-21          705920 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
  31 (0xffffa00040dd6a00) pl011-input     cpu0 waiting    vruntime   7.3464e-23           66816 console::LineDiscipline::read_poll(console::console_driver*) at drivers/line-discipline.cc:86
  32 (0xffffa00040dd6c00) rand_harvestq   cpu0 waiting    vruntime  1.23782e-20         4673264 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
    timers: 0.713837120
  33 (0xffffa00040dcf200) dhcp            cpu0 waiting    vruntime  8.49847e-21         8125296 dhcp::dhcp_worker::dhcp_worker_fn() at core/dhcp.cc:828
  34 (0xffffa00040e02c00) /tests/tst-pipe cpu0 waiting    vruntime  4.79452e-21         3974992 nanosleep(timespec const*, timespec*) at libc/time.cc:38
    timers: 1.155489872
  35 (0xffffa00040fb9400) >/tests/tst-pip cpu0 waiting    vruntime  6.99743e-23           57568 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
Number of threads: 35
```

Please note that I had to tweak `loader.py` to make the thread timers logic work correctly in gdb. I also added the `_total_cpu_time` column.

If I continue in gdb and `Ctr-C` after a while and run `osv info threads --timers` it would show exact same output with the same `_total_cpu_time` especially for the idle thread. If I press any button where OSv is running which triggers console interrupts and `Ctr-C` again and run  `osv info threads --timers` I can see `_total_cpu_time` advance for the idle thread but no change to other threads  `_total_cpu_time` and timers if any. So it seems as if no clock events are coming which if I understand OSv scheduler makes any timers expire.

I have noticed that so far the tests that hang like this, typically call some version of `sleep()` including a case when the test app completes but OSv main thread itself hangs when calling `sleep()` to DHCP release. This seems to indicate a possible problem with cooperative scheduling which is one theory. But I must stress that I see this type of hanging even with the patches fixing the `reschedule_from_interrupt` caller-save problem and many others I have found applied. What is also important I have never seen any of those tests hang when I run the same code on QEMU with KVM on. These "hangs" seem to happen in TCG mode only.

I have also discovered that when I run the following from gdb against the hung test app:
```
p sched::cpu::current()->timers.fired()
```

it makes the test proceed and complete.

So it seems maybe OSv gets into a state when the no clock alarm events are set and the scheduler never gets the events to expire relevant timers. Is my thinking correct? Or we have a bug in a schedule where we somehow mishandle receive clock event and never set the next one?

Another more likely and related possibility is that we have a bug in `arm_clock_events` (see https://github.com/cloudius-systems/osv/blob/master/arch/aarch64/arm-clock.cc#L87-L172) where we either incorrectly set a new alarm or possibly set it in a way that is mishandled on the QEMU side which never triggers an interrupt. Please remember that in TCG mode QEMU has to emulate the virtual counter registers.

Firstly, when one looks at this code:

```C++
void arm_clock_events::set(std::chrono::nanoseconds nanos)
{
    if (nanos.count() <= 0) {
        _callback->fired();
    } else {
        u64 tval = nanos.count();
        class arm_clock *c = static_cast<arm_clock *>(clock::get());
        tval = ((__uint128_t)tval * c->freq_hz) / NANO_PER_SEC;

        u32 ctl = this->read_ctl();
        ctl |= 1;  /* set enable */
        ctl &= ~2; /* unmask timer interrupt */
        this->write_tval(tval);
        this->write_ctl(ctl);
    }
}
```

he/she can notice that we ignore non-positive intervals and call `_callback->fired()` on the spot rather than setting an alarm which I understand is an optimization. Now, I think similarly the value of `tval` calculated later might also be 0 if the value of `nanos` argument is small enough given the clock frequency (for QEMU TCG the frequency is 62500000). So another optimization we can make by changing this code to this (I was hoping that this might also fix a bug):
```C++
void arm_clock_events::set(std::chrono::nanoseconds nanos)
{
    if (nanos.count() <= 0) {
        _callback->fired();
    } else {
        u64 tval = nanos.count();
        class arm_clock *c = static_cast<arm_clock *>(clock::get());
        tval = ((__uint128_t)tval * c->freq_hz) / NANO_PER_SEC;

        if (tval) {
            u32 ctl = this->read_ctl();
            ctl |= 1;  /* set enable */
            ctl &= ~2; /* unmask timer interrupt */
            this->write_tval(tval);
            this->write_ctl(ctl);
        } else {
            _callback->fired();
        }
    }
}
```

This optimization does not seem to fix the "hang" problem but I discovered that if change `if (tval) {` to `if (tval > 4) {` or `if (tval > 1000) {` for some unit tests the hang problem seems to go away. As a matter of fact, the `tst-hub.cc` (test_timer::test2() creates 5000 threads where each calls stress_thread() to randomly sleep) would always hang in TCG mode, and using even 4 for tval would make it not hang.  Some other tests required the value of 1000 in the if.

So given that I wonder if possibly QEMU has a bug where it cannot properly simulate small tval value. The ARM clock events can be armed using tval (the interval/offset counter) or cval (comparison counter):

From ARM Reference Manual:

"CNTV_TVAL_EL0, Counter-timer Virtual Timer TimerValue register

Bits [63:32]
Reserved, RES0.
TimerValue, bits [31:0]
The TimerValue view of the EL1 virtual timer.
On a read of this register:
• If CNTV_CTL_EL0.ENABLE is 0, the value returned is UNKNOWN.
• If CNTV_CTL_EL0.ENABLE is 1, the value returned is (CNTV_CVAL_EL0 - CNTVCT_EL0).
On a write of this register, CNTV_CVAL_EL0 is set to (CNTVCT_EL0 + TimerValue), where TimerValue is treated as a signed 32-bit integer.
When CNTV_CTL_EL0.ENABLE is 1, the timer condition is met when (CNTVCT_EL0 - CNTV_CVAL_EL0) is greater than or equal to zero. This means that TimerValue acts like a 32-bit downcounter timer. When the timer condition is met:
• CNTV_CTL_EL0.ISTATUS is set to 1.
• If CNTV_CTL_EL0.IMASK is 0, an interrupt is generated.
When CNTV_CTL_EL0.ENABLE is 0, the timer condition is not met, but CNTVCT_EL0 continues to count, so the TimerValue view appears to continue to count down.
This field resets to an architecturally UNKNOWN value."

"CNTV_CVAL_EL0, Counter-timer Virtual Timer CompareValue register

CompareValue, bits [63:0]
Holds the EL1 virtual timer CompareValue.
When CNTV_CTL_EL0.ENABLE is 1, the timer condition is met when (CNTVCT_EL0 - CompareValue) is greater than or equal to zero. This means that CompareValue acts like a 64-bit upcounter timer. When the timer condition is met:
• CNTV_CTL_EL0.ISTATUS is set to 1.
• If CNTV_CTL_EL0.IMASK is 0, an interrupt is generated.
When CNTV_CTL_EL0.ENABLE is 0, the timer condition is not met, but CNTVCT_EL0 continues to count.
If the Generic counter is implemented at a size less than 64 bits, then this field is permitted to be implemented at the same width as the counter, and the upper bits are RES0.
The value of this field is treated as zero-extended in all counter calculations. This field resets to an architecturally UNKNOWN value."

It seems to possible to use either counter and our code using CNTV_CVAL_EL0 works well on KVM. But for example, when I look at this code in Linux - https://github.com/torvalds/linux/blob/edd7ab76847442e299af64a761febd180d71f98d/drivers/clocksource/arm_arch_timer.c#L388-L407-  it uses CNTV_CVAL_EL0 which maybe is better emulated in QEMU. The Linux code reads CNTVCT_EL0 , adds interval in ticks, and writes to CNTV_CVAL_EL0. Maybe this is what we should be doing.

All in, it would be nice to pinpoint what precisely is going on and possibly verify my theory.

BTW I may have found a related QEMU bug - https://bugs.launchpad.net/qemu/+bug/1859021

**Comment by wkozaczuk** [comment]
This got accidentally resolved by github.
