### ISSUE TITLE
aarch64: tst-threadcomplete.cc hangs most of the time with 2 vCPUs or more

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1130]
Most of the time the test hangs in the "detach tests" phase. Connecting with gdb typically shows this thread list:
```
(gdb) osv info threads
   1 (0xffffa000407e7768) reclaimer       cpu0 waiting    vruntime  1.48634e-24            2250 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
   2 (0xffffa0004085a718) page-access-sca cpu1 waiting    vruntime  2.80272e-22          986032 sched::thread::sleep<long, std::ratio<1l, 1000000000l> >(std::chrono::duration<long, std::ratio<1l, 1000000000l> >) at /usr/include/c++/10/chrono:867
   3 (0xffffa0004086d018) page_pool_l2    cpu0 waiting    vruntime  1.04745e-20        10704664 memory::page_pool::l2::fill_thread() at core/mempool.cc:1437
   4 (0xffffa00040884ce8) itimer-real     cpu? unstarted  vruntime            0               0 sched::thread_main_c(sched::thread*) at arch/aarch64/processor.hh:27
   5 (0xffffa00040885790) itimer-virt     cpu? unstarted  vruntime            0               0 sched::thread_main_c(sched::thread*) at arch/aarch64/processor.hh:27
   6 (0xffffa000408c79a0) balancer0       cpu0 waiting    vruntime  8.52626e-07          203710 ?? at arch/aarch64/sched.S:50
   7 (0xffffa000408c8878) rcu0            cpu0 waiting    vruntime    1.202e-24            1834 osv::rcu::cpu_quiescent_state_thread::do_work() at core/rcu.cc:178
   8 (0xffffa000408da858) page_pool_l1_0  cpu0 waiting    vruntime  4.68268e-21         1349711 memory::page_pool::l1::fill_thread() at core/mempool.cc:1349
   9 (0xffffa000408ee898) percpu0         cpu0 waiting    vruntime  6.85009e-25            1041 workman::call_of_duty() at core/percpu-worker.cc:92
  10 (0xffffa00040912018) async_worker0   cpu0 waiting    vruntime  7.36708e-25            1125 async::async_worker::run() at core/async.cc:158
  11 (0xffffa00040912a48) idle0           cpu0 running    vruntime          inf      8138799058 ?? at arch/aarch64/sched.S:54
  12 (0xffffa00040924908) idle1           cpu1 running    vruntime          inf       785140373 std::_Function_handler<void(), sched::cpu::init_idle_thread()::<lambda()> >::_M_invoke(const std::_Any_data &) at /usr/include/c++/10/bits/std_function.h:291
  13 (0xffffa00040948810) >init           cpu0 waiting    vruntime  1.01609e-20         6309376 lockfree::mutex::lock() at core/lfmutex.cc:88
  14 (0xffffa0004095ea68) rcu1            cpu1 waiting    vruntime  6.72084e-24            1958 osv::rcu::cpu_quiescent_state_thread::do_work() at core/rcu.cc:178
  15 (0xffffa00040974758) thread taskq    cpu0 waiting    vruntime   8.5303e-24            2834 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  16 (0xffffa00040975948) callout         cpu0 waiting    vruntime  1.91526e-06          328623 _callout_thread() at bsd/porting/callout.cc:138
  17 (0xffffa0004098e848) page_pool_l1_1  cpu1 waiting    vruntime  1.89601e-21         1234369 memory::page_pool::l1::fill_thread() at core/mempool.cc:1349
  18 (0xffffa000409d1200) percpu1         cpu1 waiting    vruntime  1.87408e-23           14333 workman::call_of_duty() at core/percpu-worker.cc:92
  19 (0xffffa000409d1400) async_worker1   cpu1 waiting    vruntime  6.20385e-24             958 async::async_worker::run() at core/async.cc:158
  20 (0xffffa00040a9e200) system_taskq_0  cpu0 waiting    vruntime   7.4834e-24            1166 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  21 (0xffffa00040a9e400) system_taskq_1  cpu0 waiting    vruntime  7.67727e-24            1458 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  22 (0xffffa00040a9e600) system_taskq_2  cpu0 waiting    vruntime  7.31538e-24             917 synch_port::_msleep(void*, mtx*, int, char cons--Type <RET> for more, q to quit, c to continue without paging--c
t*, int) at bsd/porting/synch.cc:101
  23 (0xffffa00040a9e800) system_taskq_3  cpu0 waiting    vruntime  7.30245e-24             875 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  24 (0xffffa00040a9ea00) system_taskq_4  cpu0 waiting    vruntime  7.30245e-24             875 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  25 (0xffffa00040a9ec00) system_taskq_5  cpu0 waiting    vruntime  7.26368e-24             834 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  26 (0xffffa00040a9ee00) system_taskq_6  cpu0 waiting    vruntime   7.2766e-24             833 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  27 (0xffffa00040a96200) system_taskq_7  cpu0 waiting    vruntime   7.3283e-24             916 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  28 (0xffffa00040ab1c00) solthread-0x401 cpu0 waiting    vruntime  2.71597e-07           30876 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
  29 (0xffffa00040ab1e00) solthread-0x401 cpu0 waiting    vruntime  2.02097e-07           26374 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
  30 (0xffffa00040ada200) netisr          cpu0 waiting    vruntime  1.93612e-23            5541 netisr_osv_thread_wrapper(void (*)(void*), void*) at bsd/sys/net/netisr1.cc:26
  31 (0xffffa00040adae00) >init           cpu0 waiting    vruntime  2.49903e-20        33494501 sched::thread::join() at core/sched.cc:1370
	joining on <optimized out>
  32 (0xffffa00040e66400) virtio-net-rx   cpu0 waiting    vruntime  1.93872e-28           15167 virtio::virtio_driver::wait_for_queue(virtio::vring*, bool (virtio::vring::*)() const) at drivers/virtio.cc:158
  33 (0xffffa00040e66600) virtio-tx-0     cpu0 waiting    vruntime  8.85347e-29            2209 osv::xmitter<virtio::net::txq, 4096u, std::function<bool ()>, boost::iterators::function_output_iterator<osv::xmitter_functor<virtio::net::txq> > >::poll_until() at include/osv/percpu_xmit.hh:395
  34 (0xffffa00040e66800) virtio-tx-1     cpu1 waiting    vruntime  1.57686e-29            2583 osv::xmitter<virtio::net::txq, 4096u, std::function<bool ()>, boost::iterators::function_output_iterator<osv::xmitter_functor<virtio::net::txq> > >::poll_until() at include/osv/percpu_xmit.hh:395
  35 (0xffffa00040e66c00) virtio-blk      cpu0 waiting    vruntime  2.88608e-23           25624 virtio::virtio_driver::wait_for_queue(virtio::vring*, bool (virtio::vring::*)() const) at drivers/virtio.cc:158
  36 (0xffffa00040e66e00) virtio-rng      cpu0 waiting    vruntime  1.59175e-05         2228401 condvar::wait(lockfree::mutex*, sched::timer*) at core/condvar.cc:43
  37 (0xffffa000410b9600) pl011-input     cpu0 waiting    vruntime  1.26274e-23            5625 console::LineDiscipline::read_poll(console::console_driver*) at drivers/line-discipline.cc:86
  38 (0xffffa000410b9800) rand_harvestq   cpu0 waiting    vruntime  1.77273e-05         1180216 synch_port::_msleep(void*, mtx*, int, char const*, int) at bsd/porting/synch.cc:101
  39 (0xffffa000410b9c00) dhcp            cpu0 waiting    vruntime  2.46577e-22          292583 dhcp::dhcp_worker::dhcp_worker_fn() at core/dhcp.cc:828
  40 (0xffffa000410e8600) /tests/tst-thre cpu1 waiting    vruntime  3.15379e-20        51417921 lockfree::mutex::lock() at core/lfmutex.cc:88
 285 (0xffffa0004133a800) >/tests/tst-thr cpu1 terminated vruntime  1.62463e-23            6667 ?? at arch/aarch64/sched.S:50
 286 (0xffffa0004133aa00) >/tests/tst-thr cpu1 terminated vruntime  1.53028e-23            5666 ?? at arch/aarch64/sched.S:50
 287 (0xffffa0004133ac00) >/tests/tst-thr cpu1 terminated vruntime  1.36485e-23            3958 ?? at arch/aarch64/sched.S:50
 288 (0xffffa0004133ae00) >/tests/tst-thr cpu1 terminated vruntime  1.37131e-23            4000 ?? at arch/aarch64/sched.S:50
 289 (0xffffa00040c6d200) >/tests/tst-thr cpu1 terminated vruntime  1.31832e-23            3459 ?? at arch/aarch64/sched.S:50
 290 (0xffffa00040c6d400) >/tests/tst-thr cpu1 terminated vruntime  1.41784e-23            4458 ?? at arch/aarch64/sched.S:50
 291 (0xffffa00040c6d600) >/tests/tst-thr cpu1 terminated vruntime   1.3209e-23            3458 ?? at arch/aarch64/sched.S:50
 292 (0xffffa00040c6d800) >/tests/tst-thr cpu1 terminated vruntime  1.34805e-23            3708 ?? at arch/aarch64/sched.S:50
Number of threads: 48
```

Trying to continue from gdb and observing total cpu time for each idle thread indicates that 2nd cpu is stuck and not receiving any more events. The backtrace of the idle thread on the 2nd cpu looks like this:
```
(gdb) p sched::cpu::current()->id
$2 = 1
(gdb) bt
#0  0x00000000402e68a4 in sched::cpu::handle_incoming_wakeups (this=this@entry=0xffff800040821040)
    at /usr/include/c++/10/bits/atomic_base.h:420
#1  0x00000000402e6a8c in sched::cpu::do_idle (this=this@entry=0xffff800040821040) at core/sched.cc:441
#2  0x00000000402e6b58 in sched::cpu::idle (this=0xffff800040821040) at core/sched.cc:472
#3  0x00000000402e6b80 in operator() (__closure=<optimized out>, __closure=<optimized out>) at core/sched.cc:165
#4  std::__invoke_impl<void, sched::cpu::init_idle_thread()::<lambda()>&> (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#5  std::__invoke_r<void, sched::cpu::init_idle_thread()::<lambda()>&> (__fn=...) at /usr/include/c++/10/bits/invoke.h:153
#6  std::_Function_handler<void(), sched::cpu::init_idle_thread()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/10/bits/std_function.h:291
#7  0x00000000402e7294 in sched::thread::main (this=0xffffa00040924908) at core/sched.cc:1267
#8  sched::thread_main_c (t=0xffffa00040924908) at arch/aarch64/arch-switch.hh:160
#9  0x00000000402c04e0 in reschedule_from_interrupt () at arch/aarch64/sched.S:50
#10 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) disas
Dump of assembler code for function sched::cpu::handle_incoming_wakeups():
   0x00000000402e6874 <+0>:	stp	x29, x30, [sp, #-96]!
   0x00000000402e6878 <+4>:	mov	x1, #0x1700                	// #5888
   0x00000000402e687c <+8>:	mov	x29, sp
   0x00000000402e6880 <+12>:	stp	x21, x22, [sp, #32]
   0x00000000402e6884 <+16>:	mov	x21, x0
   0x00000000402e6888 <+20>:	add	x0, x0, x1
   0x00000000402e688c <+24>:	str	xzr, [sp, #80]
   0x00000000402e6890 <+28>:	ldr	x1, [x0]
   0x00000000402e6894 <+32>:	cbnz	x1, 0x402e6a0c <sched::cpu::handle_incoming_wakeups()+408>
   0x00000000402e6898 <+36>:	add	x0, sp, #0x50
   0x00000000402e689c <+40>:	ldr	x0, [x0]
   0x00000000402e68a0 <+44>:	cbnz	x0, 0x402e68b0 <sched::cpu::handle_incoming_wakeups()+60>
=> 0x00000000402e68a4 <+48>:	ldp	x21, x22, [sp, #32]
   0x00000000402e68a8 <+52>:	ldp	x29, x30, [sp], #96
   0x00000000402e68ac <+56>:	ret
```

I am not clear what exactly the state the 2nd cpu is in. I wonder if there is some problem with migrating threads from one cpu to another.

Another thing to note is that the test main thread is executing on the 2nd cpu as well and its backtrace looks like this:
```
(gdb) bt
#0  reschedule_from_interrupt () at arch/aarch64/sched.S:54
#1  0x00000000402e3684 in sched::cpu::schedule () at include/osv/sched.hh:1345
#2  0x00000000402e48e4 in sched::thread::wait (this=this@entry=0xffffa000410e8600) at core/sched.cc:1273
#3  0x00000000402c4908 in sched::thread::do_wait_until<sched::noninterruptible, sched::thread::dummy_lock, waiter::wait() const::{lambda()#1}>(sched::thread::dummy_lock&, waiter::wait() const::{lambda()#1}) (mtx=<synthetic pointer>..., pred=...) at include/osv/wait_record.hh:42
#4  sched::thread::wait_until<waiter::wait() const::{lambda()#1}>(waiter::wait() const::{lambda()#1}) (pred=...) at include/osv/sched.hh:1112
#5  waiter::wait (this=0x200000700d90) at include/osv/wait_record.hh:42
#6  lockfree::mutex::lock (this=0xffff800040821040, this@entry=0xffffa000409487c0) at core/lfmutex.cc:88
#7  0x00000000402e6414 in std::lock_guard<lockfree::mutex>::lock_guard (__m=..., this=<synthetic pointer>)
    at /usr/include/c++/10/bits/std_mutex.h:158
#8  lock_guard_for_with_lock<lockfree::mutex>::lock_guard_for_with_lock (lock=..., this=<synthetic pointer>) at include/osv/mutex.h:89
#9  sched::thread::reaper::add_zombie (this=0xffffa000409487c0, z=0xffffa00041869800) at core/sched.cc:1626
#10 0x000000004034a610 in pthread_detach (thread=<optimized out>) at /usr/include/c++/10/bits/unique_ptr.h:421
#11 0x000000004042f47c in std::thread::detach() ()
#12 0x00001000000231f8 in do_test (detach=<optimized out>, detach@entry=true) at /home/wkozaczuk/projects/osv/tests/tst-threadcomplete.cc:60
#13 0x00001000000222bc in main (ac=<optimized out>, av=<optimized out>) at /home/wkozaczuk/projects/osv/tests/tst-threadcomplete.cc:129
#14 0x00000000403163d8 in osv::application::run_main (this=0xffffa00040e5e210) at /usr/include/c++/10/bits/unique_ptr.h:665
#15 0x00000000403166cc in operator() (app=<optimized out>, __closure=0x0) at core/app.cc:233
#16 _FUN () at core/app.cc:235
#17 0x0000000040348674 in operator() (__closure=0xffffa000410e3300) at libc/pthread.cc:115
#18 std::__invoke_impl<void, pthread_private::pthread::pthread(void* (*)(void*), void*, sigset_t, const pthread_private::thread_attr*)::<lambda()>&> (__f=...) at /usr/include/c++/10/bits/invoke.h:60
#19 std::__invoke_r<void, pthread_private::pthread::pthread(void* (*)(void*), void*, sigset_t, const pthread_private::thread_attr*)::<lambda()>&> (__fn=...) at /usr/include/c++/10/bits/invoke.h:153
#20 std::_Function_handler<void(), pthread_private::pthread::pthread(void* (*)(void*), void*, sigset_t, const pthread_private::thread_attr*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/10/bits/std_function.h:291
#21 0x00000000402e7294 in sched::thread::main (this=0xffffa000410e8600) at core/sched.cc:1267
#22 sched::thread_main_c (t=0xffffa000410e8600) at arch/aarch64/arch-switch.hh:160
#23 0x00000000402c04e0 in reschedule_from_interrupt () at arch/aarch64/sched.S:50
#24 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by wkozaczuk** [comment]
Fixed by c953384e4e047616730ab3e8ffde8c120d02d082
