### ISSUE TITLE
F_SETLK/F_SETLKW/F_GETLK on fcntl() missing

### ISSUE THREAD

**Issue by syuu1228** [cloudius-systems/osv#185]
We don't have F_SETLK/F_SETLKW/F_GETLK on fcntl().
SQLite calls it to lock DB file.

**Comment by nyh** [comment]
These fcntl() commands are also used by Java for java.nio.channels.FileChannel.lock().
See in OpenJDK's source code, jdk/src/solaris/native/sun/nio/ch/FileDispatcherImpl.c, Java_sun_nio_ch_FileDispatcherImpl_lock0().

dominique.broeglin@gmail.com reported this on the mailing list:

Boss tries to write to its configuration files, I get an error:
```
Caused by: java.io.IOException: Invalid argument
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1072)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1053)
        at org.jboss.as.logging.logmanager.ConfigurationPersistence.writeConfiguration(ConfigurationPersistence.java:405)
```
The following code:
```java
package io.osv;

import java.io.FileOutputStream;
import java.nio.channels.FileLock;

public class Main {
  public static void main(String[] args) throws Exception {

    FileOutputStream out = new FileOutputStream("/config.txt");
    final FileLock lock = out.getChannel().lock();
[...]
```
This will produce the following exception when run:
```
io.osv.ContextFailedException: java.io.IOException: Invalid argument
        at io.osv.Context.join(Context.java:63)
        at io.osv.ContextIsolator.runSync(ContextIsolator.java:146)
        at io.osv.RunJava.main(RunJava.java:35)
Caused by: java.io.IOException: Invalid argument
        at sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:90)
        at sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1021)
        at java.nio.channels.FileChannel.lock(FileChannel.java:1052)
        at io.osv.Main.main(Main.java:11)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at io.osv.ContextIsolator.runMain(ContextIsolator.java:233)
        at io.osv.ContextIsolator.access$400(ContextIsolator.java:32)
        at io.osv.ContextIsolator$3.run(ContextIsolator.java:118)
```
