### ISSUE TITLE
Cassandra 2.1.2 does not able to boot up

### ISSUE THREAD

**Issue by syuu1228** [cloudius-systems/osv#553]
A patch for 2.1.2 is here: https://gist.github.com/syuu1228/ef2767d076894876e223

After updated to 2.1.2, Cassandra causes io.netty.channel.ChannelException on starting 0.0.0.0:9042 (CQL port).

```
INFO  20:02:23 Starting listening for CQL clients on /0.0.0.0:9042...
ERROR 20:02:23 Exception encountered during startup
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel
    at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:447) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:298) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:273) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:269) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at org.apache.cassandra.transport.Server.run(Server.java:184) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.transport.Server.start(Server.java:116) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java:390) [apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:461) [apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:537) [apache-cassandra-2.1.2.jar:2.1.2]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_55]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_55]
    at io.osv.ContextIsolator.runMain(ContextIsolator.java:233) [runjava.jar:na]
    at io.osv.ContextIsolator.access$400(ContextIsolator.java:32) [runjava.jar:na]
    at io.osv.ContextIsolator$3.run(ContextIsolator.java:118) [runjava.jar:na]
Caused by: io.netty.channel.ChannelException: java.io.IOException: Error creating socket: Protocol not supported
    at io.netty.channel.epoll.Native.socketStreamFd(Native.java:132) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.channel.epoll.EpollServerSocketChannel.<init>(EpollServerSocketChannel.java:37) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_55]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_55]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_55]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_55]
    at java.lang.Class.newInstance(Class.java:374) ~[na:1.7.0_55]
    at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:445) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    ... 15 common frames omitted
Caused by: java.io.IOException: Error creating socket: Protocol not supported
    at io.netty.channel.epoll.Native.socketStream(Native Method) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    at io.netty.channel.epoll.Native.socketStreamFd(Native.java:130) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
    ... 22 common frames omitted
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel
    at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:447)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:298)
    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:273)
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:269)
    at org.apache.cassandra.transport.Server.run(Server.java:184)
    at org.apache.cassandra.transport.Server.start(Server.java:116)
    at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java:390)
    at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:461)
    at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:537)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at io.osv.ContextIsolator.runMain(ContextIsolator.java:233)
    at io.osv.ContextIsolator.access$400(ContextIsolator.java:32)
    at io.osv.ContextIsolator$3.run(ContextIsolator.java:118)
Caused by: io.netty.channel.ChannelException: java.io.IOException: Error creating socket: Protocol not supported
    at io.netty.channel.epoll.Native.socketStreamFd(Native.java:132)
    at io.netty.channel.epoll.EpollServerSocketChannel.<init>(EpollServerSocketChannel.java:37)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at java.lang.Class.newInstance(Class.java:374)
    at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:445)
    ... 15 more
Caused by: java.io.IOException: Error creating socket: Protocol not supported
    at io.netty.channel.epoll.Native.socketStream(Native Method)
    at io.netty.channel.epoll.Native.socketStreamFd(Native.java:130)
    ... 22 more
Exception encountered during startup: Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel
INFO  20:02:23 Announcing shutdown
INFO  20:02:25 Waiting for messaging service to quiesce
pthread_kill() stubbed
ERROR 20:02:25 Exception in thread Thread[StorageServiceShutdownHook,5,main]
java.io.IOError: java.io.IOException: No such file or directory
    at org.apache.cassandra.net.MessagingService.shutdown(MessagingService.java:720) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.service.StorageService$1.runMayThrow(StorageService.java:605) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_55]
Caused by: java.io.IOException: No such file or directory
    at sun.nio.ch.NativeThread.signal(Native Method) ~[na:1.7.0_55]
    at sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:283) ~[na:1.7.0_55]
    at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:231) ~[na:1.7.0_55]
    at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115) ~[na:1.7.0_55]
    at sun.nio.ch.ServerSocketAdaptor.close(ServerSocketAdaptor.java:148) ~[na:1.7.0_55]
    at org.apache.cassandra.net.MessagingService$SocketThread.close(MessagingService.java:959) ~[apache-cassandra-2.1.2.jar:2.1.2]
    at org.apache.cassandra.net.MessagingService.shutdown(MessagingService.java:716) ~[apache-cassandra-2.1.2.jar:2.1.2]
    ... 3 common frames omitted
```

**Comment by wkozaczuk** [comment]
I do not think many people care about better supporting Cassandra on OSv. Shall we close it?

**Comment by nyh** [comment]
We should probably move this issue to the osv-apps mailing list. I don't know if it indicates a missing feature in OSv, and OSv bug, or just miscompilation. But since it's clear that nobody cares about the specific version of Cassandra mentioned on this issue, we should close this issue and open a new one when somebody wants to run newer Cassandra (probably version 3.*, or even 4.*) on OSv.
