### ISSUE TITLE
./script/build failure with GCC 5.1.0

### ISSUE THREAD

**Issue by iori-yja** [cloudius-systems/osv#634]
Compiling first example failed with ./script/build.
Ncurses library seems to be stucked.

There is closed ticket that is same as the problem here.
http://trac.sagemath.org/ticket/18301
And there're same reports, for example:
http://lists.gnu.org/archive/html/bug-ncurses/2014-07/msg00020.html

```
% ./scripts/build
Building into build/release.x64
  GEN gen/include/osv/version.h
  CXX loader.cc
  CXX bsd/sys/net/radix.cc
  CXX core/version.cc
  CXX libc/libc.cc
  LINK loader.elf

:
(snip)
:
gcc -DHAVE_CONFIG_H -I../ncurses -I.  -D_GNU_SOURCE -DNDEBUG -I. -I../include -fPIC -O2  --param max-inline-insns-single=1200 -fPIC -c ../ncurses/./base/lib_immedok.c -o ../obj_s/lib_immedok.o
In file included from ../ncurses/curses.priv.h:283:0,
                 from ../ncurses/lib_gen.c:19:
_18118.c:835:15: error: expected ‘)’ before ‘int’
../include/curses.h:1594:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
Makefile:1550: recipe for target '../obj_s/lib_gen.o' failed
make[2]: *** [../obj_s/lib_gen.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/iorivur/src/OS/osv/modules/ncurses/build/ncurses-5.9/ncurses'
Makefile:109: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/iorivur/src/OS/osv/modules/ncurses/build/ncurses-5.9'
Makefile:24: recipe for target 'build/ncurses-5.9/lib/libncurses.so' failed
make: *** [build/ncurses-5.9/lib/libncurses.so] Error 2
Traceback (most recent call last):
  File "scripts/module.py", line 241, in <module>
    args.func(args)
  File "scripts/module.py", line 198, in build
    make_modules(modules, args)
  File "scripts/module.py", line 102, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for ncurses
./scripts/build failed: jdkbase=$jdkbase ARCH=$arch OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules

```

**Comment by nyh** [comment]
Sadly, there hasn't been a new ncurses release to fix this problem, so the only thing we can do is to patch ncurses 5.9 in modules/ncurses/Makefile. I'll prepare a patch, but I don't have gcc 5.1 to test this on, so can you please test this patch when I'll send it? Thanks.

**Comment by nyh** [comment]
I just sent a patch for this to the mailing list. Can you please test it? Thanks.
