### ISSUE TITLE
no simple how-to build myapp

### ISSUE THREAD

**Issue by hartsantler** [cloudius-systems/osv#695]
following the documentation from the front page i built and ran the osv example application, with this command:
```
./scripts/build
```
This builds the default example app, which is where?
I want to build my own code now, and i do not want to use Capstan.
Running `./scripts/build image=foo` gives me this error
```
$ ./scripts/build image=foo
Building into build/release.x64
  GEN gen/include/osv/version.h
No such image configuration: foo. Assuming list of modules.
Traceback (most recent call last):
  File "scripts/module.py", line 243, in <module>
    args.func(args)
  File "scripts/module.py", line 180, in build
    api.require_running(name)
  File "/home/brett/osv/scripts/osv/modules/resolve.py", line 169, in require_running
    module = require(module_name)
  File "/home/brett/osv/scripts/osv/modules/resolve.py", line 130, in require
    raise Exception("Module not found: %s. Please check configuration: %s" % (module_name, get_config_path()))
Exception: Module not found: foo. Please check configuration: /home/brett/osv/config.json
./scripts/build failed: jdkbase=$jdkbase ARCH=$arch mode=$mode OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules
```

where should i put my `foo` folder, and what should i put inside it?

**Comment by hartsantler** [comment]
i created a folder `myapp` in `osv/apps` and now i get a more useful error.
```
./scripts/build image=myapp
Building into build/release.x64
  GEN gen/include/osv/version.h
No such image configuration: myapp. Assuming list of modules.
No module.py in /home/brett/osv/apps/myapp
Modules:
  myapp.*
Preparing usr.manifest
Preparing bootfs.manifest
Saving command line to /home/brett/osv/build/release.x64/cmdline
No apps selected
...
```
so i need to create a `module.py` in myapp folder. it would be nice if there was some documentation on this.

**Comment by hartsantler** [comment]
i put an empty `module.py` file in `apps/myapp` but i do not see how that will build my `helloworld.cc` app, we have to use Makefiles?

**Comment by hartsantler** [comment]
answering my own question: yes a `Makefile` is required.
```
brett@mintx ~/osv $ ./scripts/build image=myapp
Building into build/release.x64
  GEN gen/include/osv/version.h
No such image configuration: myapp. Assuming list of modules.
Importing /home/brett/osv/apps/myapp/module.py
Modules:
  myapp.*
make: *** No rule to make target `module'.  Stop.
```

**Comment by hartsantler** [comment]
i setup my Makefile, and myapp.so now compiles, but i am not sure how to setup `usr.manifest` file.
here is the error i get now:
```
Preparing usr.manifest
Appending /home/brett/osv/apps/pythia_build/usr.manifest to usr.manifest
Preparing bootfs.manifest
Saving command line to /home/brett/osv/build/release.x64/cmdline
No apps selected
OSv v0.24-25-gb32e6d9
eth0: 192.168.122.15
Running mkfs...
strip: './myapp.so': No such file
Traceback (most recent call last):
  File "/home/brett/osv/scripts/upload_manifest.py", line 206, in <module>
    main()
  File "/home/brett/osv/scripts/upload_manifest.py", line 198, in main
    upload(osv, manifest, depends)
  File "/home/brett/osv/scripts/upload_manifest.py", line 150, in upload
    perm = os.stat(hostname).st_mode & 0o777
OSError: [Errno 2] No such file or directory: './myapp-stripped.so'

```

this is my usr.manifest
```
/tools/myapp.so: ./myapp.so
```
not sure what i am doing wrong in the manifest.

**Comment by hartsantler** [comment]
i managed to get my hello world working, after looking through the code and directory structure.  Really would have been helpful if there were docs on this of course.
For anybody else who is also lost on the basic steps to make hello world, you can follow my steps and notes here:
https://github.com/secureosv/pythia/commit/53f34ef214e1afd3fddf368d75e280569fc631f6

**Comment by tgrabiec** [comment]
Extending OSv using the module system is documented here: https://github.com/cloudius-systems/osv/wiki/OSv-modules
