### ISSUE TITLE
Attribute Error on Crm_case on odoo7

### ISSUE THREAD

**Issue by saqibgilani79** [cloudius-systems/osv#759]
Client Traceback (most recent call last):
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\http.py", line 204, in dispatch
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\controllers\main.py", line 1137, in call_button
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\controllers\main.py", line 1125, in _call_kw
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\session.py", line 42, in proxy
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\session.py", line 30, in proxy_method
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\session.py", line 103, in send

Server Traceback (most recent call last):
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\web\session.py", line 89, in send
  File "C:\Program Files (x86)\odoo7\server\.\openerp\netsvc.py", line 306, in dispatch_rpc
  File "C:\Program Files (x86)\odoo7\server\.\openerp\service\web_services.py", line 632, in dispatch
  File "C:\Program Files (x86)\odoo7\server\.\openerp\osv\osv.py", line 190, in execute_kw
  File "C:\Program Files (x86)\odoo7\server\.\openerp\osv\osv.py", line 132, in wrapper
  File "C:\Program Files (x86)\odoo7\server\.\openerp\osv\osv.py", line 199, in execute
  File "C:\Program Files (x86)\odoo7\server\.\openerp\osv\osv.py", line 187, in execute_cr
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\base\module\module.py", line 428, in button_immediate_install
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\base\module\module.py", line 475, in _button_immediate_function
  File "C:\Program Files (x86)\odoo7\server\.\openerp\pooler.py", line 39, in restart_pool
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\registry.py", line 233, in new
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\loading.py", line 355, in load_modules
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\loading.py", line 256, in load_marked_modules
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\loading.py", line 159, in load_module_graph
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\module.py", line 405, in load_openerp_module
  File "C:\Program Files (x86)\odoo7\server\.\openerp\modules\module.py", line 133, in load_module
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\call_center\__init__.py", line 21, in <module>
  File "C:\Program Files (x86)\odoo7\server\openerp\addons\call_center\call_center_opener.py", line 47, in <module>
AttributeError: 'module' object has no attribute 'crm_case'

**Comment by nyh** [comment]
Again, I think you are in the wrong OSv project... This OSv is an operating system, not some python module in a CRM application.

**Comment by saqibgilani79** [comment]
Sir, please advise what i have to do ... i want to install call_Center module.

**Comment by penberg** [comment]
@saqibgilani79 We have no idea -- this is not the project you are using.
