### ISSUE TITLE
Go requiring unimplemented vdso page

### ISSUE THREAD

**Issue by benoit-canet** [cloudius-systems/osv#794]
After the pending patches on the osv-dev list if I insert an abort before sending SIGSEGV to the program
and track it with gdb I get.

```
(gdb) bt
#0  0x000000000038d732 in processor::cli_hlt () at arch/x64/processor.hh:247
#1  arch::halt_no_interrupts () at arch/x64/arch.hh:48
#2  osv::halt () at arch/x64/power.cc:24
#3  0x0000000000225b17 in abort (fmt=fmt@entry=0x6ffd1e "abort") at runtime.cc:130
#4  0x0000000000328c0c in mmu::vm_sigsegv (addr=<optimized out>, ef=0xffff800003712078) at core/mmu.cc:1312
#5  mmu::vm_fault (addr=<optimized out>, addr@entry=18446744073699065856, ef=ef@entry=0xffff800003712078) at core/mmu.cc:1339
#6  0x0000000000386ef9 in page_fault (ef=0xffff800003712078) at arch/x64/mmu.cc:38
#7  <signal handler called>
#8  0xffffffffff600000 in ?? ()
#9  0x0000100000d1e3d8 in runtime.nanotime () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:188
#10 0x0000100000ce7e87 in runtime.(*mheap).freeSpanLocked (h=0x100001057b60 <runtime.mheap_>, s=0x200000204000, acctinuse=false, acctidle=true, unusedsince=0) at /usr/lib/golang/src/runtime/mheap.go:774
#11 0x0000100000ce7a61 in runtime.(*mheap).grow (h=0x100001057b60 <runtime.mheap_>, npage=8, ~r1=false) at /usr/lib/golang/src/runtime/mheap.go:675
#12 0x0000100000ce7668 in runtime.(*mheap).allocSpanLocked (h=0x100001057b60 <runtime.mheap_>, npage=1, ~r1=0x6) at /usr/lib/golang/src/runtime/mheap.go:553
#13 0x0000100000ce6cad in runtime.(*mheap).alloc_m (h=0x100001057b60 <runtime.mheap_>, npage=1, sizeclass=21, large=false, ~r3=0x2000001ffa18) at /usr/lib/golang/src/runtime/mheap.go:437
#14 0x0000100000d121c3 in runtime.(*mheap).alloc.func1 () at /usr/lib/golang/src/runtime/mheap.go:502
#15 0x0000100000d1afe1 in runtime.systemstack () at /usr/lib/golang/src/runtime/asm_amd64.s:307
#16 0x0000100000ce7005 in runtime.(*mheap).alloc (h=0x100001057b60 <runtime.mheap_>, npage=1, sizeclass=21, large=false, needzero=true, ~r4=0x100000cd3fe8 <runtime.lock+136>)
    at /usr/lib/golang/src/runtime/mheap.go:503
#17 0x0000100000cda805 in runtime.(*mcentral).grow (c=0x100001059760 <runtime.mheap_+7168>, ~r0=0x0) at /usr/lib/golang/src/runtime/mcentral.go:209
#18 0x0000100000cda1bf in runtime.(*mcentral).cacheSpan (c=0x100001059760 <runtime.mheap_+7168>, ~r0=0x1000010547a8 <runtime.globalAlloc+8>) at /usr/lib/golang/src/runtime/mcentral.go:89
#19 0x0000100000cd9a60 in runtime.(*mcache).refill (c=0x200000200000, sizeclass=21, ~r1=0x2000001ffb88) at /usr/lib/golang/src/runtime/mcache.go:119
#20 0x0000100000d10dfd in runtime.mallocgc.func2 () at /usr/lib/golang/src/runtime/malloc.go:642
#21 0x0000100000d1afe1 in runtime.systemstack () at /usr/lib/golang/src/runtime/asm_amd64.s:307
#22 0x0000100000cd5bbc in runtime.mallocgc (size=384, typ=0x100000fcf740, flags=0, ~r3=0x800000000) at /usr/lib/golang/src/runtime/malloc.go:643
#23 0x0000100000cd5f44 in runtime.newobject (typ=0x100000fcf740, ~r1=0x100001054a30 <runtime.sched+16>) at /usr/lib/golang/src/runtime/malloc.go:781
#24 0x0000100000cf8679 in runtime.malg (stacksize=32768, ~r1=0x100001054ca0 <runtime.g0>) at /usr/lib/golang/src/runtime/proc.go:2637
#25 0x0000100000ced3c1 in runtime.mpreinit (mp=0x100001054fe0 <runtime.m0>) at /usr/lib/golang/src/runtime/os1_linux.go:205
#26 0x0000100000cf2b29 in runtime.mcommoninit (mp=0x100001054fe0 <runtime.m0>) at /usr/lib/golang/src/runtime/proc.go:497
#27 0x0000100000cf267d in runtime.schedinit () at /usr/lib/golang/src/runtime/proc.go:434
#28 0x0000100000d1adb4 in runtime.rt0_go () at /usr/lib/golang/src/runtime/asm_amd64.s:138
#29 0x0000000000000001 in ?? ()
#30 0x00002000001ffd90 in ?? ()
#31 0x0000000000000001 in ?? ()
#32 0x00002000001ffd90 in ?? ()
#33 0x00002000001ffe30 in ?? ()
#34 0x000000000040d8f6 in osv::application::run_main (this=<error reading variable: Cannot access memory at address 0xffffffffffffffb0>, path=...,
    argc=<error reading variable: Cannot access memory at address 0xffffffffffffffcc>, argv=<optimized out>) at core/app.cc:338
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) frame 9
#9  0x0000100000d1e3d8 in runtime.nanotime () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:188
188             CALL    AX
(gdb) list
183             RET
184     fallback:
185             LEAQ    0(SP), DI
186             MOVQ    $0, SI
187             MOVQ    runtime·__vdso_gettimeofday_sym(SB), AX
188             CALL    AX
189             MOVQ    0(SP), AX       // sec
190             MOVL    8(SP), DX       // usec
191             IMULQ   $1000, DX
192             // sec is in AX, nsec in DX
(gdb) p $ax
$1 = 0
(gdb)
```

**Comment by wkozaczuk** [comment]
I wonder if this commit https://github.com/cloudius-systems/osv/commit/6454485dd590a590bb6c64149fd0b0ddd9aa5b7a addresses this issue ?

**Comment by nyh** [comment]
Yes, I believe so. Thanks.
