### ISSUE TITLE
fread on raw block device triggers "Assertion failed: (uio->uio_resid % BSIZE) == 0"

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#877]
Patch to add libcdio is in https://groups.google.com/forum/#!topic/osv-dev/osGUGP-TGqY.

The test code is:
```
The iso-read tries first to read 'superblock', and that already fails (below, vblok0 is used, so that I don't need tosend a valid iso image):

scripts/build mode=debug image=cli,libcdio -j4
./scripts/run.py -d --novnc -V -e '/usr/bin/iso-read.so -e user-data -o /tmp/config.yaml -d 1 -k /dev/vblk0; /cli/cli.so'
Assertion failed: (uio->uio_resid % BSIZE) == 0 (fs/vfs/vfs_bdev.cc: bdev_read: 40)

[backtrace]
0x000000000022cc16 <abort(char const*, ...)+270>
0x000000000022cc77 <__assert_fail+58>
0x0000000000673506 <bdev_read+190>
0x000000000044dac2 <???+4512450>
0x000000000067fb8f <device_read+127>
0x000000000067f068 <???+6811752>
0x000000000067cdd3 <vfs_file::read(uio*, int)+133>
0x0000000000679cd9 <sys_read+382>
0x0000000000648764 <preadv64+80>
0x00000000006487d3 <readv+41>
0x00000000006921d2 <__stdio_read+152>
0x00000000006da653 <fread_unlocked+292>
0x000010000600906b <???+100700267>
0x00001000060094b5 <cdio_stream_read+96>
0x0000100006406786 <???+104884102>
0x00001000064067bc <iso9660_iso_seek_read+51>
0x0000100006405f0d <???+104881933>
0x0000100006405f6f <???+104882031>
0x0000100006405fb2 <iso9660_ifs_read_superblock+64>
0x000010000640594a <???+104880458>
0x0000100006405a36 <???+104880694>
0x0000100006405a09 <???+104880649>
0x000010000580214e <???+92283214>
0x0000100005802705 <???+92284677>
0x00000000006397ad <osv::application::run_main(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, char**)+713>
0x0000000000639a01 <osv::application::run_main()+329>
0x00000000006394b0 <osv::application::main()+108>
0x0000000000638ec7 <???+6524615>
0x0000000000638eeb <???+6524651>
0x000000000069e95c <???+6941020>
0x00000000006a1427 <???+6951975>
0x00000000004437d1 <std::function<void ()>::operator()() const+49>
0x00000000005ba237 <sched::thread::main()+27>
0x00000000005b610b <thread_main_c+38>
0x00000000004808d2 <???+4720850>
0x2138fddc0b3520ff <???+188031231>
0x00000000005b9aaf <sched::thread::~thread()+651>
0xa4b8bab87d894847 <???+2106148935>

 246 (0xffff800004340040) timerfd         cpu0 status::waiting waiter::wait(sched::timer*) const at include/osv/wait_record.hh:47 vruntime  1.10635e-23
 247 (0xffff80000440d040) /usr/bin/iso-re cpu0 status::running processor::cli_hlt() at arch/x64/processor.hh:248 vruntime -1.23547e-20
Number of threads: 141
Missing separate debuginfos, use: dnf debuginfo-install boost-filesystem-1.60.0-10.fc25.x86_64 boost-regex-1.60.0-10.fc25.x86_64 boost-system-1.60.0-10.fc25.x86_64 yaml-cpp-0.5.1-13.fc24.x86_64
(gdb) 
(gdb) osv thr 247
(gdb) bt
#0  processor::cli_hlt () at arch/x64/processor.hh:248
#1  0x0000000000209ca8 in arch::halt_no_interrupts () at arch/x64/arch.hh:48
#2  0x0000000000490b15 in osv::halt () at arch/x64/power.cc:24
#3  0x000000000022cc3d in abort (fmt=0xa13d28 "Assertion failed: %s (%s: %s: %d)\n") at runtime.cc:130
#4  0x000000000022cc78 in __assert_fail (expr=0xacaccf "(uio->uio_resid % BSIZE) == 0", file=0xacac78 "fs/vfs/vfs_bdev.cc", line=40, func=0xacad08 <bdev_read::__func__> "bdev_read") at runtime.cc:137
#5  0x0000000000673507 in bdev_read (dev=0xffffa00002437d00, uio=0x2000002fe8a0, ioflags=0) at fs/vfs/vfs_bdev.cc:40
#6  0x000000000044dac3 in virtio::blk_read (dev=0xffffa00002437d00, uio=0x2000002fe8a0, ioflags=0) at drivers/virtio-blk.cc:72
#7  0x000000000067fb90 in device_read (dev=0xffffa00002437d00, uio=0x2000002fe8a0, ioflags=0) at fs/devfs/device.cc:384
#8  0x000000000067f069 in devfs_read (vp=0xffffa00004311580, fp=0xffffa00004311500, uio=0x2000002fe8a0, ioflags=0) at fs/devfs/devfs_vnops.cc:107
#9  0x000000000067cdd4 in vfs_file::read (this=0xffffa00004311500, uio=0x2000002fe8a0, flags=0) at fs/vfs/vfs_fops.cc:54
#10 0x0000000000679cda in sys_read (fp=0xffffa00004311500, iov=0x2000002fe9a0, niov=2, offset=-1, count=0x2000002fe938) at fs/vfs/vfs_syscalls.cc:275
#11 0x0000000000648765 in preadv (fd=8, iov=0x2000002fe9a0, iovcnt=2, offset=-1) at fs/vfs/main.cc:418
#12 0x00000000006487d4 in readv (fd=8, iov=0x2000002fe9a0, iovcnt=2) at fs/vfs/main.cc:434
#13 0x00000000006921d3 in __stdio_read (f=0xffff900004046000, buf=0xffff800004413051 "", len=2048) at libc/stdio/__stdio_read.c:33
#14 0x00000000006da654 in fread (destv=0xffff800004413051, size=1, nmemb=2048, f=0xffff900004046000) at musl/src/stdio/fread.c:27
#15 0x000010000600906c in _stdio_read (user_data=0xffffa00004304fe0, buf=0xffff800004413051, count=2048) at _cdio_stdio.c:212
#16 0x00001000060094b6 in cdio_stream_read (p_obj=0xffffa00004311600, ptr=0xffff800004413051, size=2048, nmemb=1) at _cdio_stream.c:156
#17 0x0000100006406787 in iso9660_seek_read_framesize (p_iso=0xffff800004413040, ptr=0xffff800004413051, start=16, size=1, i_framesize=2048) at iso9660_fs.c:694
#18 0x00001000064067bd in iso9660_iso_seek_read (p_iso=0xffff800004413040, ptr=0xffff800004413051, start=16, size=1) at iso9660_fs.c:704
#19 0x0000100006405f0e in iso9660_ifs_read_pvd_loglevel (p_iso=0xffff800004413040, p_pvd=0xffff800004413051, log_level=CDIO_LOG_WARN) at iso9660_fs.c:444
#20 0x0000100006405f70 in iso9660_ifs_read_pvd (p_iso=0xffff800004413040, p_pvd=0xffff800004413051) at iso9660_fs.c:458
#21 0x0000100006405fb3 in iso9660_ifs_read_superblock (p_iso=0xffff800004413040, iso_extension_mask=0 '\000') at iso9660_fs.c:474
#22 0x000010000640594b in iso9660_open_ext_private (psz_path=0xffff900003ffd000 "/dev/vblk0", iso_extension_mask=0 '\000', i_fuzz=0, b_fuzzy=false) at iso9660_fs.c:181
#23 0x0000100006405a37 in iso9660_open_ext (psz_path=0xffff900003ffd000 "/dev/vblk0", iso_extension_mask=0 '\000') at iso9660_fs.c:220
#24 0x0000100006405a0a in iso9660_open (psz_path=0xffff900003ffd000 "/dev/vblk0") at iso9660_fs.c:209
#25 0x000010000580214f in read_iso_file (iso_name=0xffff900003ffd000 "/dev/vblk0", src=0xffff900003ffe000 "user-data", outfd=0xffff90000404a000, bytes_written=0x2000002ffc98) at iso-read.c:217
#26 0x0000100005802706 in main (argc=9, argv=0x2000002ffcd0) at iso-read.c:370
#27 0x00000000006397ae in osv::application::run_main (this=0xffffa000042fe510, path="/usr/bin/iso-read.so", argc=9, argv=0xffffa00004311200) at core/app.cc:334
#28 0x0000000000639a02 in osv::application::run_main (this=0xffffa000042fe510) at core/app.cc:351
#29 0x00000000006394b1 in osv::application::main (this=0xffffa000042fe510) at core/app.cc:279
#30 0x0000000000638ec8 in osv::application::<lambda(void*)>::operator()(void *) const (__closure=0x0, app=0xffffa000042fe510) at core/app.cc:197
#31 0x0000000000638eec in osv::application::<lambda(void*)>::_FUN(void *) () at core/app.cc:199
#32 0x000000000069e95d in pthread_private::pthread::<lambda()>::operator()(void) const (__closure=0xffffa0000432cf00) at libc/pthread.cc:114
#33 0x00000000006a1428 in std::_Function_handler<void(), pthread_private::pthread::pthread(void* (*)(void*), void*, sigset_t, const pthread_private::thread_attr*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/6.3.1/functional:1731
#34 0x00000000004437d2 in std::function<void ()>::operator()() const (this=0xffff80000440d070) at /usr/include/c++/6.3.1/functional:2127
#35 0x00000000005ba238 in sched::thread::main (this=0xffff80000440d040) at core/sched.cc:1208
#36 0x00000000005b610c in sched::thread_main_c (t=0xffff80000440d040) at arch/x64/arch-switch.hh:164
#37 0x00000000004808d3 in thread_main () at arch/x64/entry.S:113

#13 0x00000000006921d3 in __stdio_read (f=0xffff900004046000, buf=0xffff800004413051 "", len=2048) at libc/stdio/__stdio_read.c:33
33			cnt = readv(f->fd, iov, 2);
(gdb) p iov
$1 = {{iov_base = 0xffff800004413051, iov_len = 2047}, {iov_base = 0xffff900004046108, iov_len = 1024}}
```
I already have some debug printf s in my code, so libc/stdio/__stdio_read.c:33 should be line 28
https://github.com/cloudius-systems/osv/blob/master/libc/stdio/__stdio_read.c#L28

The https://github.com/cloudius-systems/osv/blob/master/libc/stdio/__stdio_read.c#L18
has two "!!", which I relay down understand (what it does - I get that, but - why?).

I will try to continue with libcdio by replacing __stdio_read with something else.

**Comment by justinc1** [comment]
After change in osv/modules/libcdio/build/libcdio-0.94/src
diff --git a/lib/driver/_cdio_stdio.c b/lib/driver/_cdio_stdio.c
index 805cc69..b9a899b 100644
--- a/lib/driver/_cdio_stdio.c
+++ b/lib/driver/_cdio_stdio.c
@@ -209,7 +209,7 @@ _stdio_read(void *user_data, void *buf, size_t count)
   _UserData *const ud = user_data;
   long read_count;
 
-  read_count = fread(buf, 1, count, ud->fd);
+  read_count = read(ud->fd, buf, count); /**/
 
   if (read_count != count)
     { /* fixme -- ferror/feof */


The same test returns:
++ WARN: unexpected PVD type 0
iso-read.so: Sorry, couldn't open ISO-9660 image file 'user-data'.
program /usr/bin/iso-read.so returned 1
/#
/#

So this looks like OSv fread problem to me.

**Comment by nyh** [comment]
I think there are two issues here:
1. Understand why OSv doesn't support unaligned reads (here 2047 bytes) from block device. Those will obviously be inefficient, but do not necessarily have to fail. Do they also fail on Linux?
2. Understand why stdio asks for 2047, not 2048 bytes! You're right that the "!!" stuff is very fishy - why read 2048-1 bytes? Looks like a bug but I haven't looked at this code for a long time, I have to understand again what it does :-)

Also, with read(), did you expect that error you showed or it's also a bug?

**Comment by justinc1** [comment]
With read, I expected the read() will return some data (it does, so this is ok). As I was testing with vblk0 (HDD with mbr and zfs etc), I exepcted that no valid ISO signature will be found - I guess that is the meaning of " WARN: unexpected PVD type 0". So with read(), I think the iso-read actually works.
