### ISSUE TITLE
openjdk8-fedora fails when building for ramfs

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#879]
```
./scripts/build -j4 mode=release image=openjdk8-fedora fs=ramfs
...
Saving command line to /home/justin_cinkelj/devel/mikelangelo/osv-fc25/osv/build/release.x64/cmdline
No apps selected
Building into build/release.x64
  GEN gen/include/osv/version.h
  CXX loader.cc
  CXX core/version.cc
  CXX libc/libc.cc
  MKBOOTFS build/release.x64/bootfs.bin
strip: '!/home/justin_cinkelj/devel/mikelangelo/osv-fc25/osv/apps/openjdk8-fedora/install/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b12.fc27.x86_64/jre/lib/amd64/server/libjsig.so': No such file
Traceback (most recent call last):
  File "/home/justin_cinkelj/devel/mikelangelo/osv-fc25/osv/scripts/mkbootfs.py", line 154, in <module>
    main()
  File "/home/justin_cinkelj/devel/mikelangelo/osv-fc25/osv/scripts/mkbootfs.py", line 127, in main
    size = os.stat(hostname).st_size
OSError: [Errno 2] No such file or directory: '!/home/justin_cinkelj/devel/mikelangelo/osv-fc25/osv/apps/openjdk8-fedora/install/usr/lib/.build-id/a2/636fa308771ed6effe33bd558b4b0fbf6a991a'
make: *** [build/release.x64/bootfs.bin] Error 1
Makefile:1877: recipe for target 'build/release.x64/bootfs.bin' failed
make: *** Deleting file 'build/release.x64/bootfs.bin'
make: *** Waiting for unfinished jobs....
make failed. Exiting from build script

```

Only "./scripts/build -j4 mode=release image=openjdk8-fedora" works.

What is meaning of ! in front of filename in usr.manifest? Dereference symbolic link maybe?

**Comment by nyh** [comment]
I can reproduce the same problem. 
It seems a bug in scripts/mkbootfs.py. It needs to remove the '!' like upload_manifest.py does. I don't remember why this exists :-) I'll need to investigate.

**Comment by justinc1** [comment]
Following your hint, I added 2 lines:
```
diff --git a/scripts/mkbootfs.py b/scripts/mkbootfs.py
index 8cda3b0..ee45ee0 100755
--- a/scripts/mkbootfs.py
+++ b/scripts/mkbootfs.py
@@ -30,6 +30,8 @@ def expand(items):
             yield (name, hostname)
 
 def unsymlink(f):
+    if f.startswith('!'):
+        f = f[1:]
     try:
         link = os.readlink(f)
         if link.startswith('/'):
```

Now I can compile "./scripts/build -j4 mode=release image=openjdk8-zulu-compact3-with-java-beans fs=ramfs". That usr.manifiest also contains lines like "/aa   !/bb/cc", so I guess this fixed the problem.

The image=openjdk8-fedora case however still fails, but with entirely different error:
```
  LZ loader-stripped.elf
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/sh: line 1: 13586 Aborted                 (core dumped) build/release.x64/fastlz/lz build/release.x64/loader-stripped.elf
make: *** [build/release.x64/loader-stripped.elf.lz.o] Error 134
Makefile:457: recipe for target 'build/release.x64/loader-stripped.elf.lz.o' failed
make failed. Exiting from build script
```
A new issue I guess.
