### ISSUE TITLE
tst-condvar crashs on qemu 2.10

### ISSUE THREAD

**Issue by geraldo-netto** [cloudius-systems/osv#950]
Dear Friends,

I have updated qemu in order to re-test some test units that were failing but I have found another issue
Once again, I'll try to do more tests and will report accordingly

netto@vmx01 ~/Downloads/osv-clean $ qemu-system-x86_64 -version
QEMU emulator version 2.10.1(Debian 1:2.10+dfsg-0ubuntu3.5)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
netto@vmx01 ~/Downloads/osv-clean $ make check
...
  TEST tst-condvar.so
OSv v0.24-499-g58c358d
Aborted

[backtrace]
0x0000000000293edd <vcmn_err+173>
0x00000000002f1ade <zfs_panic_recover+158>
0x00000000002ed491 <space_map_remove+641>
0x00000000002ed808 <space_map_walk+56>
0x00000000002dd449 <metaslab_sync+617>
0x00000000002f69ca <vdev_sync+106>
0x00000000002e66da <spa_sync+938>
0x00000000002f2b0d <???+3091213>
0x00000000003e5d76 <thread_main_c+38>
0x0000000000388f82 <???+3706754>
Test tst-condvar.so FAILED
Traceback (most recent call last):
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 187, in <module>
    main()
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 174, in main
    run_tests()
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 165, in run_tests
    run(tests_to_run)
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 85, in run
    run_test(test)
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 60, in run_test
    test.run()
  File "/home/netto/Downloads/osv-clean/scripts/tests/testing.py", line 29, in run
    run_command_in_guest(self.command).join()
  File "/home/netto/Downloads/osv-clean/scripts/tests/testing.py", line 163, in join
    raise Exception('Guest failed')
Exception: Guest failed
Makefile:143: recipe for target 'check' failed
make: *** [check] Error 1

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
Can you report specifics of your setup? I have never seen this test fail (at least on on Ubuntu 16.04/QEMU 2.5 and 18.04/2.11/.

Do you use KVM?

**Comment by geraldo-netto** [comment]
Hello @wkozaczuk ,

I'm closing this ticket because I cannot reproduce it now
So, it was probably something between the chair and the laptop! :)

Kind Regards,
Geraldo Netto
