### ISSUE TITLE
tracing_smoke_test failure

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#988]
There was a one-time (so far...) failure of tracing_smoke_test on the Jenkins machine, http://jenkins.cloudius-systems.com:8080/job/osv-build-nightly/1534/console

A snippet from the log:
```
TEST tracing_smoke_test                 Traceback (most recent call last):
  File "./scripts/trace.py", line 798, in <module>
    args.func(args)
  File "./scripts/trace.py", line 445, in print_summary
    timed = timed_producer(t)
  File "/var/lib/jenkins/jobs/osv-build-nightly/workspace/scripts/osv/prof.py", line 230, in __call__
    raise Exception('Nested entry:\n%s\n%s\n' % (str(old), str(sample)))
Exception: Nested entry:
0xffff8000027ce040 >init            1         0.151872120 sched_wait              [0x3e0127, 0x3e4e00, 0x372ea4, 0x34d8b1, 0x34ab8b, 0x34d6e9, 0x375f39, 0x2131a9, 0x449455, 0x3e5296]
0xffff8000027ce040 >init            1         0.249565960 sched_wait              [0x3e0127, 0x3e4508, 0x3c4a67, 0x2faae5, 0x3223c1, 0x321529, 0x2f7bea, 0x2f7aef, 0x2f9505, 0x2e6971]

Test tracing_smoke_test FAILED
```

**Comment by nyh** [comment]
Failed again: http://jenkins.cloudius-systems.com:8080/job/osv-build-nightly/1602/console
